/**
 * generated by Xtext 2.10.1
 */
package org.xtext.example.eaa.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.eaa.myDsl.MyDslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
