/**
 * generated by Xtext 2.10.1
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ui.AbstractSmallUMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SmallUMLUiModule extends AbstractSmallUMLUiModule {
  public SmallUMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
