/**
 * generated by Xtext 2.10.1
 */
package org.xtext.example.eaa;

import org.xtext.example.eaa.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
