/*
 * generated by Xtext 2.10.1
 */
package org.xtext.example.eaa.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
