/**
 * generated by Xtext 2.10.1
 */
package org.xtext.ui.contentassist;

import org.xtext.ui.contentassist.AbstractSmallUMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SmallUMLProposalProvider extends AbstractSmallUMLProposalProvider {
}
