/**
 * generated by Xtext 2.10.1
 */
package org.xtext;

import org.xtext.SmallUMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallUMLStandaloneSetup extends SmallUMLStandaloneSetupGenerated {
  public static void doSetup() {
    SmallUMLStandaloneSetup _smallUMLStandaloneSetup = new SmallUMLStandaloneSetup();
    _smallUMLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
