/**
 * generated by Xtext 2.10.1
 */
package org.xtext;

import org.xtext.AbstractSmallUMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallUMLRuntimeModule extends AbstractSmallUMLRuntimeModule {
}
