/*
 * generated by Xtext 2.10.1
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmallUMLScopeProvider extends DelegatingScopeProvider {
}
