/**
 * generated by Xtext 2.10.1
 */
package org.xtext.scoping;

import org.xtext.scoping.AbstractSmallUMLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SmallUMLScopeProvider extends AbstractSmallUMLScopeProvider {
}
