/**
 * generated by Xtext 2.10.1
 */
package org.xtext.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.tests.SmallUMLInjectorProvider;
import smalluml.SchemaUML;

@RunWith(XtextRunner.class)
@InjectWith(SmallUMLInjectorProvider.class)
@SuppressWarnings("all")
public class SmallUMLParsingTest {
  @Inject
  private ParseHelper<SchemaUML> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final SchemaUML result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
