/**
 *
 * $Id$
 */
package EAA.validation;

import EAA.Association;
import EAA.Entity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link EAA.Schema}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SchemaValidator {
	boolean validate();

	boolean validateAss(EList<Association> value);
	boolean validateE(EList<Entity> value);
}
