/*
 * generated by Xtext 2.10.1
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.SmallUML.ui.internal.SmallUMLActivator;

public class SmallUMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmallUMLActivator.getInstance().getInjector("org.xtext.SmallUML");
	}

}
