/**
 *
 * $Id$
 */
package smalluml.validation;

import org.eclipse.emf.common.util.EList;

import smalluml.Attribute;
import smalluml.Role;
import smalluml.SmallClass;

/**
 * A sample validator interface for {@link smalluml.Association}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSource(SmallClass value);
	boolean validateCible(SmallClass value);
	boolean validateListeAttribute(EList<Attribute> value);
	boolean validateListeRole(EList<Role> value);
}
