/**
 *
 * $Id$
 */
package smalluml.validation;

import org.eclipse.emf.common.util.EList;

import smalluml.Association;
import smalluml.Generalisation;
import smalluml.SmallClass;

/**
 * A sample validator interface for {@link smalluml.SchemaUML}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SchemaUMLValidator {
	boolean validate();

	boolean validateGene(EList<Generalisation> value);
	boolean validateC(EList<SmallClass> value);
	boolean validateAss(EList<Association> value);
}
