/*
 * generated by Xtext 2.10.1
 */
package org.xtext.example.eaa


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
